### ISSUE TITLE
能否详细说明一下http转发授权

### ISSUE THREAD

**Issue by HenryXiaoYang** [sayue2019/wechat-service-allin#3]
我调用api时死活调用不了，还以为是hook注入问题，结果发现有这个http转发

能否写一份文档说明一下这个http转发，如何授权啥的，谢谢！

**Comment by HenryXiaoYang** [comment]
还有能否禁用这个功能，继续使用hook提供的api端口

**Comment by sayue2019** [comment]
禁用可以将build-injector-box.sh脚本文件中把最下面几行中的 run_http_frward 那行注释掉，

http转发相关配置可以查看示例 docker-compose.yaml 在文件中的环境变量设置
```sh
            #HTTP要转发地址设置
            FORWARD_URL: "http://127.0.0.1:5555"
            #http转发服务端口设置
            LISTEN_PORT: "8888"
            #http访问密码设置
            ACCESS_PASSWORD: "password"
            FOR_CONDITION: "[ \"`sudo netstat -tunlp | grep 8888`\" != '' ] && exit 0"
```
http转发是考虑外网安全性对原服务增加了一层访问授权，示例docker-compose.yaml设置并未开放容器中hook服务的端口，你也直接开启hook服务的端口忽视转发功能。

**Comment by HenryXiaoYang** [comment]
谢谢解释！
