### ISSUE TITLE
如果要转发的http地址是8080，和vnc的端口是不是就冲突了

### ISSUE THREAD

**Issue by pengfeiu** [sayue2019/wechat-service-allin#5]
如何修改vnc内部端口

**Comment by pengfeiu** [comment]
改代理地址也行

**Comment by sayue2019** [comment]
确实，你提到的端口冲突问题是可能发生的。为了解决这个问题，我已经在项目中添加了一个专门用于配置 VNC 端口的文件。你可以通过编辑这个配置文件来自定义 VNC 的端口，从而避免与其他服务的端口冲突。

要使用这个新特性，请按照以下步骤操作：

**更新脚本**：首先，请确保你的 build-injector-box.sh 脚本是最新版本的。这个脚本现在包含了更新的步骤，用于处理 VNC 配置文件。
**调整 VNC 配置**：在 vnc 目录中，你会找到新的配置文件。打开它，按照你的需要修改 VNC 端口设置。
通过这些更改，你可以自由配置 VNC 端口，以确保它不会与 HTTP 服务的端口冲突。如果你在操作过程中遇到任何问题，欢迎随时提问。
